import {ORDER,origins,beasts,jobs,isEligible,compatible,startValues} from './data.js';
const skillData=await fetch('./skills.json').then(r=>r.json());
const $=s=>document.querySelector(s),grid=$('#dice-grid'),list=$('#origin-list');
const full={COU:'Courage',INT:'Intelligence',CHA:'Charisme',AD:'Adresse',FOR:'Force'};
for(const key of ORDER){const div=document.createElement('div');div.className='die';div.innerHTML=`<label for="die-${key}">${key}</label><input id="die-${key}" name="${key}" type="number" inputmode="numeric" min="1" max="6" step="1" required aria-label="Résultat du dé pour ${full[key]}"><small>${full[key]}</small>`;grid.append(div)}
let data=[],mode='all';
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const statText=s=>ORDER.map(k=>`<span>${k} <strong>${s[k]}</strong></span>`).join('');
const formatNum=n=>Number.isInteger(n)?String(n):String(n).replace('.',',');
function skillHTML(name){const info=skillData[name];if(!info)return '';return `<details class="skill-details"><summary>Compétences de la fiche</summary><p><strong>Acquises :</strong> ${escape(info.born.join(' · ')||'Selon la fiche du métier')}</p><p><strong>Au choix :</strong> ${escape(info.choices.join(' · '))}</p></details>`}
function scenarios(rolls){const original=Object.fromEntries(ORDER.map((k,i)=>[k,rolls[i]+7]));const out=[{stats:original,label:'Sans échange',direct:true}];const seen=new Set([ORDER.map(k=>original[k]).join(',')]);for(let i=0;i<5;i++)for(let j=i+1;j<5;j++){const scores={...original};[scores[ORDER[i]],scores[ORDER[j]]]=[scores[ORDER[j]],scores[ORDER[i]]];const hash=ORDER.map(k=>scores[k]).join(',');if(!seen.has(hash)){out.push({stats:scores,label:`Échanger ${ORDER[i]} ↔ ${ORDER[j]}`,direct:false});seen.add(hash)}}return out}
function expandOrigins(){return origins.flatMap(o=>o.beast?beasts.map((v,i)=>({...o,name:`Homme-bête · ${v.name}`,ev:v.ev,beastDelta:v.delta,beastIndex:i+1})):o)}
function eligibleForScenario(origin,s){if(!origin.beastDelta)return isEligible(s.stats,origin);return isEligible(s.stats,{...origin,beastDelta:undefined})}
function effectiveStats(o,s){if(!o.beastDelta)return s.stats;const stats={...s.stats};for(const [key,delta] of Object.entries(o.beastDelta))stats[key]+=delta;return stats}
function makeData(rolls){const variants=scenarios(rolls);return expandOrigins().map(origin=>({origin,options:variants.filter(s=>eligibleForScenario(origin,s))})).filter(x=>x.options.length)}
function jobHTML(o,s){let base=effectiveStats(o,s),available=o.bundle?[]:jobs.filter(j=>isEligible(base,j)&&compatible(o,j));const originNum=startValues(base,o,null);const jobsHtml=available.map(j=>{const v=startValues(base,o,j);let evLabel=v.ev==null?'Selon la version':formatNum(v.ev)+(Number.isInteger(v.ev)?'':' · arrondi à préciser');return `<article class="job"><h4>${escape(j.name)}</h4><div class="numbers">EV ${evLabel} · AT ${v.at} · PRD ${v.prd}${v.ea!=null?` · EA ${v.ea}`:''}</div><p>${escape(j.note||'EV selon l’origine.')}${v.adChoice?' · '+v.adChoice:''}</p>${skillHTML(j.name)}</article>`}).join('');let baseValue=`EV ${formatNum(originNum.ev)} · AT ${originNum.at} · PRD ${originNum.prd}${originNum.ea!=null?` · EA ${originNum.ea}`:''}`;
 return `<div class="stat-strip" aria-label="Caractéristiques obtenues">${statText(base)}</div><p class="source-value"><strong>Profil de base :</strong> ${escape(baseValue)}. ${originNum.adChoice?escape(originNum.adChoice)+'. ':''}${originNum.impact?`Impact ${originNum.impact>0?'+':''}${originNum.impact}. `:''}${originNum.spell?`Dégâts des sorts concernés +${originNum.spell}. `:''}</p>${o.beastDelta?'<p>Version tirée au D6 ; les métiers sont évalués après ses modifications de caractéristiques. L’ordre de vérification des plafonds reste à confirmer avec le MJ.</p>':''}${skillHTML(o.beastDelta?'Homme-bête':o.name)}<h3 class="job-heading">${o.bundle?'Profil complet':'Métiers accessibles avec ces scores'}</h3><div class="job-list">${o.bundle?'<article class="job nocareer"><h4>Origine et métier réunis</h4><p>Les compétences et valeurs propres à cette fiche remplacent celles d’une combinaison standard.</p></article>':jobsHtml+'<article class="job nocareer"><h4>Sans métier</h4><p>Possibilité de choisir un métier à partir du niveau 3. EV et AT/PRD du profil de base ci-dessus.</p></article>'}</div>`}
function render(){const displayed=data.filter(d=>mode==='all'||(mode==='direct'?d.options.some(x=>x.direct):d.options.some(x=>!x.direct)));list.innerHTML=displayed.map((item,i)=>{const {origin:o,options}=item;const optionsForMode=options.filter(x=>mode==='direct'?x.direct:mode==='swap'?!x.direct:true);const s=optionsForMode[0],direct=mode!=='swap'&&options.some(x=>x.direct);const optHtml=optionsForMode.map((x,n)=>`<option value="${n}">${escape(x.label)} · ${ORDER.map(k=>x.stats[k]).join(' / ')}</option>`).join('');return `<details class="origin ${direct?'direct':'swap-only'}" data-origin="${escape(o.name)}" ${i===0?'open':''}><summary><div><div class="origin-title">${escape(o.name)}${o.bundle?'<span class="pill">Profil complet</span>':''}${o.unofficial?'<span class="pill fan">Non officiel</span>':''}</div><div class="origin-sub">${optionsForMode.length} répartition${optionsForMode.length>1?'s':''} compatible${optionsForMode.length>1?'s':''} · ${direct?'Accessible sans échange':'Échange nécessaire'}${o.beastIndex?` · D6 : ${o.beastIndex}`:''}</div></div><span class="pill ${direct?'':'swap'}">${direct?'Direct':'Échange'}</span></summary><div class="origin-body"><p>${escape(o.note||'')}</p>${optionsForMode.length>1?`<label class="scenario-label" for="choice-${i}">Répartition à examiner</label><select class="scenario-select" id="choice-${i}" data-index="${i}">${optHtml}</select>`:`<span class="scenario-label">${escape(s.label)}</span>`}<div class="scenario-content">${jobHTML(o,s)}</div></div></details>`}).join('');if(!displayed.length)list.innerHTML='<p>Aucun profil ne correspond à ce filtre.</p>';list.querySelectorAll('select').forEach(select=>select.addEventListener('change',()=>{const item=displayed[Number(select.dataset.index)];const variants=item.options.filter(x=>mode==='direct'?x.direct:mode==='swap'?!x.direct:true);select.closest('.origin-body').querySelector('.scenario-content').innerHTML=jobHTML(item.origin,variants[Number(select.value)])}))}
$('#dice-form').addEventListener('submit',event=>{event.preventDefault();const raw=ORDER.map(k=>Number($(`#die-${k}`).value)),invalid=raw.some((n,i)=>!Number.isInteger(n)||n<1||n>6||$(`#die-${ORDER[i]}`).value.trim()==='');if(invalid){$('#form-error').hidden=false;$('#form-error').textContent='Indiquez cinq résultats entiers compris entre 1 et 6.';return}$('#form-error').hidden=true;data=makeData(raw);mode='all';document.querySelectorAll('.mode').forEach(b=>b.classList.toggle('active',b.dataset.mode==='all'));const original=Object.fromEntries(ORDER.map((k,i)=>[k,raw[i]+7]));$('#roll-summary').innerHTML=ORDER.map(k=>`${k} ${original[k]}`).join(' · ');const direct=data.filter(x=>x.options.some(s=>s.direct)).length;$('#summary-badges').innerHTML=`<span>${direct} profil${direct>1?'s':''} direct${direct>1?'s':''}</span><span>${data.length-direct} autre${data.length-direct>1?'s':''} avec échange</span>`;$('#results').hidden=false;render();$('#results').scrollIntoView({behavior:'smooth',block:'start'})});
document.querySelectorAll('.mode').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.mode;document.querySelectorAll('.mode').forEach(x=>x.classList.toggle('active',x===b));render()}));
