import {ORDER,origins,beasts,jobs,isEligible,compatible,startValues,derivedValues} from './data.js';
import {SENSES} from './creation-rules.js';
import {profileLimits} from './profile-limits.js';
import {BEAST_DETAILS} from './creation-details.js';
const skillData=await fetch('./skills.json').then(r=>r.json());
const skillHints=await fetch('./skill-hints.json').then(r=>r.json());
const genericSkills=await fetch('./generic-skills.json').then(r=>r.json());
const $=s=>document.querySelector(s),grid=$('#dice-grid'),list=$('#origin-list');
const full={COU:'Courage',INT:'Intelligence',CHA:'Charisme',AD:'Adresse',FOR:'Force'};
// Les cinq dés se règlent au toucher ; une nouvelle pression avance d'une face.
const diceDots={1:[5],2:[1,9],3:[1,5,9],4:[1,3,7,9],5:[1,3,5,7,9],6:[1,3,4,6,7,9]};
function face(value){return `<span class="d6-pips" aria-hidden="true">${Array.from({length:9},(_,i)=>`<i class="${diceDots[value]?.includes(i+1)?'shown':''}"></i>`).join('')}</span>`;}
for(const key of ORDER){const div=document.createElement('div');div.className='die';div.innerHTML=`<span class="die-label" id="die-label-${key}">${key}</span><input id="die-${key}" name="${key}" type="hidden"><button type="button" class="d6-button" data-die="${key}" aria-describedby="die-label-${key}" aria-label="${full[key]} : dé à régler">${face(0)}</button><small>${full[key]}</small>`;grid.append(div)}
function setDie(key,value){const input=$(`#die-${key}`),button=grid.querySelector(`[data-die="${key}"]`);input.value=value;button.innerHTML=face(value);button.setAttribute('aria-label',`${full[key]} : ${value} sur le dé, appuyer pour afficher ${value%6+1}`);}
grid.addEventListener('click',event=>{const button=event.target.closest('[data-die]');if(button){const key=button.dataset.die;setDie(key,(Number($(`#die-${key}`).value)%6)+1);}});
let data=[],mode='all';
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const statText=s=>ORDER.map(k=>`<span>${k} <strong>${s[k]}</strong></span>`).join('');
const formatNum=n=>Number.isInteger(n)?String(n):String(n).replace('.',',');
function skillNameHTML(name){const hint=skillHints[name];return hint?`<span class="skill-with-tip"><button type="button" class="skill-name" aria-label="${escape(name)} : ${escape(hint)}">${escape(name)}</button><span class="skill-tip" role="tooltip">${escape(hint.replace(/^Utilisation\s*:\s*/i,''))}</span></span>`:escape(name)}
function skillHTML(name){const info=skillData[name];if(!info)return '';return `<details class="skill-details" open><summary>Compétences de la fiche</summary><p><strong>Acquises :</strong> ${info.born.map(skillNameHTML).join(' · ')||'Selon la fiche du métier'}</p><p><strong>Au choix :</strong> ${info.choices.map(skillNameHTML).join(' · ')}</p></details>`}
const skillKey=name=>String(name).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]/g,'').toLowerCase();
function choiceSkills(origin,job){
 const o=skillData[origin.beastDelta?'Homme-bête':origin.name]||{born:[],choices:[]};
 const j=job?skillData[job.name]||{born:[],choices:[]}:{born:[],choices:[]};
 const born=new Set([...o.born,...(BEAST_DETAILS[origin.name]?.born||[]),...j.born].map(skillKey));
 const options=job?.name==='Sbire'?[...o.choices,...genericSkills]:[...o.choices,...j.choices];
 const names=options.filter(n=>!born.has(skillKey(n))&&skillKey(n)!=='appeldusauvage'&&(!job?.magic||skillKey(n)!=='tetevide')&&(job?.name!=='Sbire'||!['chefdegroupe','chercherdesnoises'].includes(skillKey(n))));
 return [...new Map(names.map(n=>[skillKey(n),n])).values()];
}
function choiceSkillsHTML(origin,job){
 const o=skillData[origin.beastDelta?'Homme-bête':origin.name]||{born:[]};
 const j=job?skillData[job.name]||{born:[]}:{born:[]};
 const born=[...new Map([...o.born,...(BEAST_DETAILS[origin.name]?.born||[]),...j.born].map(n=>[skillKey(n),n])).values()];
 const acquired=born.length?`<details class="skill-details"><summary>Compétences déjà acquises (${born.length})</summary><p>${born.map(skillNameHTML).join(' · ')}</p></details>`:'';
 if(origin.name==='Humain')return `<p class="selection-note">${job?'Deux compétences du métier et une compétence générique':'Trois compétences génériques'} à choisir en page 2.</p>${acquired}`;
 const names=choiceSkills(origin,job);
 return `<p class="selection-note">${origin.bundle?'Deux compétences du profil':'Deux compétences parmi l’origine et le métier'} à choisir en page 2.</p><p class="skill-choices">${names.map(skillNameHTML).join(' · ')||'Voir les compétences du profil en page 2.'}</p>${acquired}`;
}
function perceptionHTML(origin){
 const sense=SENSES[origin.beastDelta?'Homme-bête':origin.name]||{};
 const labels=[['vue','Vue'],['ouie','Ouïe'],['odorat','Odorat']];
 const output=labels.filter(([key])=>sense[key]).map(([key,label])=>`${label} ${sense[key]>0?'+':''}${sense[key]}`);
 if(sense.nuit)output.push(`Nyctalopie ${sense.nuit}`);
 return output.length?`<p class="selection-note"><strong>Perception :</strong> ${output.map(escape).join(' · ')}.</p>`:'';
}
function statDice(stats){return `<span class="swap-stats" aria-label="Scores après échange : ${ORDER.map(k=>`${k} ${stats[k]}`).join(', ')}">${ORDER.map(k=>`<span class="swap-die"><small>${k}</small><strong>${stats[k]}</strong></span>`).join('')}</span>`;}
function scenarios(rolls){const original=Object.fromEntries(ORDER.map((k,i)=>[k,rolls[i]+7]));const out=[{stats:original,label:'Sans échange',direct:true}];const seen=new Set([ORDER.map(k=>original[k]).join(',')]);for(let i=0;i<5;i++)for(let j=i+1;j<5;j++){const scores={...original};[scores[ORDER[i]],scores[ORDER[j]]]=[scores[ORDER[j]],scores[ORDER[i]]];const hash=ORDER.map(k=>scores[k]).join(',');if(!seen.has(hash)){out.push({stats:scores,label:`Échanger ${ORDER[i]} ↔ ${ORDER[j]}`,direct:false});seen.add(hash)}}return out}
function expandOrigins(){return origins}
function eligibleForScenario(origin,s){return isEligible(s.stats,origin)}
function effectiveStats(o,s){if(!o.beastDelta)return s.stats;const stats={...s.stats};for(const [key,delta] of Object.entries(o.beastDelta))stats[key]+=delta;return stats}
function makeData(rolls){const variants=scenarios(rolls);return expandOrigins().map(origin=>({origin,options:variants.filter(s=>eligibleForScenario(origin,s))})).filter(x=>x.options.length)}
function overviewGroup(direct,bundles=false,exchangeLabel=null){
 const entries=data.flatMap(({origin,options},originIndex)=>options.flatMap((scenario,scenarioIndex)=>{
  if(bundles!==null&&Boolean(origin.bundle)!==bundles || scenario.direct!==direct || exchangeLabel!==null&&scenario.label!==exchangeLabel)return [];
  const compatibleJobs=origin.bundle||origin.beast?[]:jobs.filter(job=>isEligible(effectiveStats(origin,scenario),job)&&compatible(origin,job));
  return [{origin,originIndex,scenario,scenarioIndex,compatibleJobs}];
 }));
 const name=exchangeLabel|| (bundles?'Profils complets':'Sans échange');
 return `<section class="possibility-group ${bundles?'bundle-group':direct?'direct-group':'swap-group'}"><div class="possibility-heading"><span class="possibility-icon" aria-hidden="true">${direct?'✦':'⇄'}</span><div><h3>${escape(name)}</h3><p>${entries.length} possibilité${entries.length>1?'s':''} de répartition</p></div></div><div class="possibility-entries">${entries.map(({origin,originIndex,scenario,scenarioIndex,compatibleJobs})=>`<div class="possibility-entry"><strong class="origin-name">${escape(origin.name)}</strong><div class="job-tags">${origin.bundle?`<button type="button" data-origin-index="${originIndex}" data-scenario-index="${scenarioIndex}" data-job="bundle">Profil complet</button>`:origin.beast?`<button type="button" data-origin-index="${originIndex}" data-scenario-index="${scenarioIndex}" data-job="beast">Choisir Homme-bête · D6 et métier en page 2</button>`:compatibleJobs.map(j=>`<button type="button" data-origin-index="${originIndex}" data-scenario-index="${scenarioIndex}" data-job="${escape(j.name)}">${escape(j.name)}</button>`).join('')+`<button type="button" class="no-job" data-origin-index="${originIndex}" data-scenario-index="${scenarioIndex}" data-job="none">Sans métier</button>`}</div></div>`).join('')||'<p>Aucune origine possible.</p>'}</div></section>`;
}
function swapOverview(){
 const labels=new Set(data.flatMap(({options})=>options.filter(s=>!s.direct).map(s=>s.label)));
 const ordered=[];for(let i=0;i<ORDER.length;i++)for(let j=i+1;j<ORDER.length;j++){
  const label=`Échanger ${ORDER[i]} ↔ ${ORDER[j]}`;
  if(labels.has(label))ordered.push(label);
 }
 return `<section class="exchange-browser"><h3>Avec un échange</h3><p>Ouvrez la paire de caractéristiques qui vous intéresse pour voir les origines et métiers accessibles.</p><div class="exchange-groups">${ordered.map(label=>{
  const count=data.reduce((total,{options})=>total+options.filter(s=>s.label===label).length,0);
  const match=data.flatMap(({options})=>options).find(s=>s.label===label);
  return `<details class="exchange-group"><summary><span class="swap-header"><span>${escape(label.replace('Échanger ',''))}</span>${statDice(match.stats)}</span><small>${count} possibilité${count>1?'s':''}</small></summary>${overviewGroup(false,null,label)}</details>`;
 }).join('')||'<p>Aucun échange supplémentaire n’ouvre de possibilité.</p>'}</div></section>`;
}
function selectionHTML(origin,scenario,job){
 const stats=effectiveStats(origin,scenario),v=startValues(stats,origin,job),derived=derivedValues(stats);
 const title=job?`${origin.name} · ${job.name}`:origin.bundle||origin.beast?origin.name:`${origin.name} · Sans métier`;
 const notes=[origin.note,job?.note].filter(Boolean),limits=profileLimits(origin,job);
 const allowMagic=Boolean(job?.magic||['Mage culinaire hobbit','Chamane de jungle','Paladin semi-homme de Picrate','Paladin semi-homme de Jord’hun'].includes(origin.name));
 return `<div class="selection-heading"><p class="eyebrow">COMBINAISON CHOISIE</p><h3>${escape(title)}</h3><p>${escape(scenario.label)}${origin.unofficial?' · Supplément non officiel':''}</p></div><a class="primary continue-link mobile-continue" href="creation.html">Valider et continuer →</a>${origin.beast?'<p class="selection-note special-rule"><strong>Étape suivante :</strong> lancez 1D6 pour déterminer la variante Homme-bête, puis choisissez parmi les métiers compatibles avec ses scores modifiés.</p>':''}<div class="stat-strip">${statText(stats)}</div><div class="value-grid"><span><small>Énergie vitale</small><strong>${v.ev==null?'À déterminer':formatNum(v.ev)}</strong></span><span><small>Énergie astrale</small><strong>${v.ea==null?'–':formatNum(v.ea)}</strong></span><span><small>Attaque</small><strong>${formatNum(v.at)}</strong></span><span><small>Parade</small><strong>${formatNum(v.prd)}</strong></span></div><div class="derived-grid"><span>MAGPHYS <strong>${derived.magphys}</strong></span><span>MAGPSY <strong>${derived.magpsy}</strong></span><span>RESMAG <strong>${derived.resmag}</strong></span></div><div class="limit-grid"><span><small>PR Max</small><strong>${limits.pr??'Aucune limite chiffrée'}</strong></span><span><small>Poids maximal porté</small><strong>${limits.kg==null?'Aucune limite chiffrée':`${limits.kg} kg`}</strong></span></div>${limits.naturalPr!=null?`<p class="selection-note">PR naturelle maximale : ${limits.naturalPr} ; armures selon la fiche.</p>`:''}${limits.weapons.length?`<p class="selection-note"><strong>Armes et boucliers :</strong> ${limits.weapons.map(escape).join(' · ')}.</p>`:''}${perceptionHTML(origin)}${notes.map(note=>`<p class="selection-note">${escape(note)}</p>`).join('')}${origin.name==='Humain'&&!job?'<p class="selection-note special-rule"><strong>Humain sans métier :</strong> choisissez trois compétences parmi toutes les compétences du jeu. Un métier pourra être choisi à partir du niveau 3, si les conditions sont remplies.</p>':''}${v.adChoice?`<p class="selection-note">${escape(v.adChoice)}</p>`:''}${v.impact?`<p class="selection-note">PI ${v.impact>0?'+':''}${v.impact} grâce à la Force.</p>`:''}${allowMagic&&v.spell?`<p class="selection-note">PI magiques +${v.spell} pour les sorts concernés grâce à l’Intelligence.</p>`:''}<section class="selected-skills"><h4>Compétences à choisir au niveau 1</h4>${choiceSkillsHTML(origin,job)}</section><a class="primary continue-link" href="creation.html">Valider cet archétype et continuer →</a>`;
}
function renderOverview(){const panel=$('#possibilities');panel.innerHTML=overviewGroup(true)+swapOverview()+overviewGroup(true,true);panel.querySelectorAll('[data-job]').forEach(button=>button.addEventListener('click',()=>{panel.querySelectorAll('[data-job]').forEach(b=>b.classList.toggle('chosen',b===button));const {origin,options}=data[Number(button.dataset.originIndex)],scenario=options[Number(button.dataset.scenarioIndex)];const job=button.dataset.job==='none'||button.dataset.job==='bundle'?null:jobs.find(j=>j.name===button.dataset.job);sessionStorage.setItem('naheul-selection',JSON.stringify({origin:origin.name,job:job?.name??null,stats:scenario.stats,label:scenario.label}));sessionStorage.removeItem('naheul-draft');$('#selection-panel').innerHTML=selectionHTML(origin,scenario,job);if(window.innerWidth<790)$('#selection-panel').scrollIntoView({behavior:'smooth',block:'start'})}))}
function jobHTML(o,s){let base=effectiveStats(o,s),available=o.bundle?[]:jobs.filter(j=>isEligible(base,j)&&compatible(o,j));const originNum=startValues(base,o,null);const jobsHtml=available.map(j=>{const v=startValues(base,o,j);let evLabel=v.ev==null?'Selon la version':formatNum(v.ev);return `<article class="job"><h4>${escape(j.name)}</h4><div class="numbers">EV ${evLabel} · AT ${v.at} · PRD ${v.prd}${v.ea!=null?` · EA ${v.ea}`:''}</div><p>${escape(j.note||'EV selon l’origine.')}${v.adChoice?' · '+v.adChoice:''}</p>${skillHTML(j.name)}</article>`}).join('');let baseValue=`EV ${originNum.ev==null?'À déterminer au D6':formatNum(originNum.ev)} · AT ${originNum.at} · PRD ${originNum.prd}${originNum.ea!=null?` · EA ${originNum.ea}`:''}`;
 return `<div class="stat-strip" aria-label="Caractéristiques obtenues">${statText(base)}</div><p class="source-value"><strong>Profil de base :</strong> ${escape(baseValue)}. ${originNum.adChoice?escape(originNum.adChoice)+'. ':''}${originNum.impact?`Impact ${originNum.impact>0?'+':''}${originNum.impact}. `:''}${originNum.spell?`Dégâts des sorts concernés +${originNum.spell}. `:''}</p>${o.beastDelta?'<p>Version tirée au D6 ; les métiers sont évalués après ses modifications de caractéristiques. L’ordre de vérification des plafonds reste à confirmer avec le MJ.</p>':''}${skillHTML(o.beastDelta?'Homme-bête':o.name)}<h3 class="job-heading">${o.bundle?'Profil complet':'Métiers accessibles avec ces scores'}</h3><div class="job-list">${o.beast?'<article class="job nocareer"><h4>Variante à tirer au D6</h4><p>Choix du métier après le tirage en page 2.</p></article>':o.bundle?'<article class="job nocareer"><h4>Origine et métier réunis</h4><p>Les compétences et valeurs propres à cette fiche remplacent celles d’une combinaison standard.</p></article>':jobsHtml+'<article class="job nocareer"><h4>Sans métier</h4><p>Possibilité de choisir un métier à partir du niveau 3. EV et AT/PRD du profil de base ci-dessus.</p></article>'}</div>`}
function render(){const displayed=data.filter(d=>mode==='all'||(mode==='direct'?d.options.some(x=>x.direct):d.options.some(x=>!x.direct)));list.innerHTML=displayed.map((item,i)=>{const {origin:o,options}=item;const optionsForMode=options.filter(x=>mode==='direct'?x.direct:mode==='swap'?!x.direct:true);const s=optionsForMode[0],direct=mode!=='swap'&&options.some(x=>x.direct);const optHtml=optionsForMode.map((x,n)=>`<option value="${n}">${escape(x.label)} · ${ORDER.map(k=>x.stats[k]).join(' / ')}</option>`).join('');return `<details class="origin ${direct?'direct':'swap-only'}" data-origin="${escape(o.name)}" ${i===0?'open':''}><summary><div><div class="origin-title">${escape(o.name)}${o.bundle?'<span class="pill">Profil complet</span>':''}${o.unofficial?'<span class="pill fan">Non officiel</span>':''}</div><div class="origin-sub">${optionsForMode.length} répartition${optionsForMode.length>1?'s':''} compatible${optionsForMode.length>1?'s':''} · ${direct?'Accessible sans échange':'Échange nécessaire'}${o.beastIndex?` · D6 : ${o.beastIndex}`:''}</div></div><span class="pill ${direct?'':'swap'}">${direct?'Direct':'Échange'}</span></summary><div class="origin-body"><p>${escape(o.note||'')}</p>${optionsForMode.length>1?`<label class="scenario-label" for="choice-${i}">Répartition à examiner</label><select class="scenario-select" id="choice-${i}" data-index="${i}">${optHtml}</select>`:`<span class="scenario-label">${escape(s.label)}</span>`}<div class="scenario-content">${jobHTML(o,s)}</div></div></details>`}).join('');if(!displayed.length)list.innerHTML='<p>Aucun profil ne correspond à ce filtre.</p>';list.querySelectorAll('select').forEach(select=>select.addEventListener('change',()=>{const item=displayed[Number(select.dataset.index)];const variants=item.options.filter(x=>mode==='direct'?x.direct:mode==='swap'?!x.direct:true);select.closest('.origin-body').querySelector('.scenario-content').innerHTML=jobHTML(item.origin,variants[Number(select.value)])}))}
$('#dice-form').addEventListener('submit',event=>{event.preventDefault();const raw=ORDER.map(k=>Number($(`#die-${k}`).value)),invalid=raw.some((n,i)=>!Number.isInteger(n)||n<1||n>6||$(`#die-${ORDER[i]}`).value.trim()==='');if(invalid){$('#form-error').hidden=false;$('#form-error').textContent='Indiquez cinq résultats entiers compris entre 1 et 6.';return}$('#form-error').hidden=true;data=makeData(raw);sessionStorage.removeItem('naheul-selection');sessionStorage.removeItem('naheul-draft');$('#selection-panel').innerHTML='<div class="empty-selection"><span aria-hidden="true">✧</span><h3>Votre personnage prend forme ici</h3><p>Choisissez une origine et un métier dans la liste. Leurs caractéristiques et compétences apparaîtront à cet endroit.</p></div>';mode='all';document.querySelectorAll('.mode').forEach(b=>b.classList.toggle('active',b.dataset.mode==='all'));const original=Object.fromEntries(ORDER.map((k,i)=>[k,raw[i]+7]));$('#roll-summary').innerHTML=ORDER.map(k=>`${k} ${original[k]}`).join(' · ');const direct=data.filter(x=>x.options.some(s=>s.direct)).length;$('#summary-badges').innerHTML=`<span>${direct} profil${direct>1?'s':''} direct${direct>1?'s':''}</span><span>${data.length-direct} autre${data.length-direct>1?'s':''} avec échange</span>`;$('#results').hidden=false;renderOverview();render();$('#results').scrollIntoView({behavior:'smooth',block:'start'})});
document.querySelectorAll('.mode').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.mode;document.querySelectorAll('.mode').forEach(x=>x.classList.toggle('active',x===b));render()}));
function rollDie(){if(!globalThis.crypto?.getRandomValues)return 1+Math.floor(Math.random()*6);const draw=new Uint8Array(1);do{crypto.getRandomValues(draw)}while(draw[0]>=252);return draw[0]%6+1}
$('#roll-random').addEventListener('click',()=>{for(const key of ORDER)setDie(key,rollDie());$('#dice-form').requestSubmit()});
